#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <cerrno>
#include <fcntl.h>
#include <iostream>
#include <memory>
#include <mutex>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sstream>
#include <stdexcept>
#include <string>
#include <thread>
#include <unistd.h>
#include <vector>

#include <onnxruntime_cxx_api.h>
#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/bool.hpp>
#include <unitree_hg/msg/low_cmd.hpp>
#include <unitree_hg/msg/low_state.hpp>

#include "g1_ballet_onnx_deploy/g1_abi.hpp"
#include "g1_ballet_onnx_deploy/motor_crc_hg.hpp"

namespace g1_ballet {
namespace {

using SteadyClock = std::chrono::steady_clock;
using SteadyTime = SteadyClock::time_point;

std::string trim(std::string s) {
  const auto first = s.find_first_not_of(" \t\r\n");
  if (first == std::string::npos) return {};
  const auto last = s.find_last_not_of(" \t\r\n");
  return s.substr(first, last - first + 1);
}

std::vector<std::string> split_strings(const std::string &s) {
  std::vector<std::string> out;
  std::stringstream ss(s);
  std::string item;
  while (std::getline(ss, item, ',')) out.push_back(trim(item));
  return out;
}

std::vector<float> split_floats(const std::string &s) {
  std::vector<float> out;
  std::stringstream ss(s);
  std::string item;
  while (std::getline(ss, item, ',')) {
    item = trim(item);
    if (!item.empty()) out.push_back(std::stof(item));
  }
  return out;
}

template <size_t N>
std::array<float, N> to_array(const std::vector<float> &v, const char *name) {
  if (v.size() != N) {
    throw std::runtime_error(
        std::string(name) + " must contain " + std::to_string(N) +
        " values; got " + std::to_string(v.size()));
  }
  std::array<float, N> a{};
  std::copy(v.begin(), v.end(), a.begin());
  return a;
}

bool finite_array(const std::array<float, kNumJoints> &values) {
  return std::all_of(values.begin(), values.end(), [](float x) { return std::isfinite(x); });
}

}  // namespace

class OnnxPolicy {
 public:
  explicit OnnxPolicy(const std::string &path)
      : env_(ORT_LOGGING_LEVEL_WARNING, "g1_ballet"), opts_(), session_(nullptr) {
    opts_.SetIntraOpNumThreads(1);
    opts_.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    session_ = Ort::Session(env_, path.c_str(), opts_);

    if (session_.GetInputCount() != 1 || session_.GetOutputCount() != 1) {
      throw std::runtime_error("Ballet ONNX must have exactly one input and one output");
    }

    Ort::AllocatorWithDefaultOptions alloc;
    input_name_holder_ = session_.GetInputNameAllocated(0, alloc);
    output_name_holder_ = session_.GetOutputNameAllocated(0, alloc);
    input_name_ = input_name_holder_.get();
    output_name_ = output_name_holder_.get();

    const auto input_info = session_.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo();
    const auto output_info = session_.GetOutputTypeInfo(0).GetTensorTypeAndShapeInfo();
    if (input_info.GetElementType() != ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT ||
        output_info.GetElementType() != ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT) {
      throw std::runtime_error("Ballet ONNX input/output tensors must be float32");
    }
    const auto ishape = input_info.GetShape();
    const auto oshape = output_info.GetShape();
    if (ishape.empty() || ishape.back() != static_cast<int64_t>(kObsDim)) {
      throw std::runtime_error("ONNX input last dimension must be 186");
    }
    if (oshape.empty() || oshape.back() != static_cast<int64_t>(kNumJoints)) {
      throw std::runtime_error("ONNX output last dimension must be 29");
    }

    auto md = session_.GetModelMetadata();
    auto get_md = [&](const char *key) -> std::string {
      auto p = md.LookupCustomMetadataMapAllocated(key, alloc);
      if (!p) {
        throw std::runtime_error(std::string("ONNX metadata missing required key: ") + key);
      }
      return std::string(p.get());
    };

    const auto names = split_strings(get_md("joint_names"));
    if (names.size() != kNumJoints) {
      throw std::runtime_error("joint_names metadata is not 29D");
    }
    for (size_t i = 0; i < kNumJoints; ++i) {
      if (names[i] != kJointNames[i]) {
        throw std::runtime_error(
            "Joint order mismatch at index " + std::to_string(i) + ": ONNX=" + names[i] +
            " expected=" + std::string(kJointNames[i]));
      }
    }

    // Names are generated by mjlab.rl.exporter_utils.get_base_metadata from
    // observation_manager.active_terms["actor"].  The first term is named
    // base_ang_vel in the BALLET training config even though its physical
    // source is LowState.imu_state.gyroscope.
    const auto obs_names = split_strings(get_md("observation_names"));
    static const std::vector<std::string> expected_obs = {
        "base_ang_vel",
        "imu_lin_acc",
        "projected_gravity",
        "velocity_commands",
        "joint_pos",
        "joint_vel",
        "actions",
        "axis_actual_normalized",
        "axis_target_normalized",
        "axis_mask",
    };
    if (obs_names != expected_obs) {
      std::ostringstream got;
      for (size_t i = 0; i < obs_names.size(); ++i) {
        if (i) got << ',';
        got << obs_names[i];
      }
      throw std::runtime_error(
          "ONNX observation_names do not match ballet actor ABI; got [" + got.str() + "]");
    }

    default_q_ = to_array<kNumJoints>(split_floats(get_md("default_joint_pos")), "default_joint_pos");
    action_scale_ = to_array<kNumJoints>(split_floats(get_md("action_scale")), "action_scale");
    kp_ = to_array<kNumJoints>(split_floats(get_md("joint_stiffness")), "joint_stiffness");
    kd_ = to_array<kNumJoints>(split_floats(get_md("joint_damping")), "joint_damping");

    if (!finite_array(default_q_) || !finite_array(action_scale_) ||
        !finite_array(kp_) || !finite_array(kd_)) {
      throw std::runtime_error("ONNX deployment metadata contains NaN/Inf");
    }
  }

  std::array<float, kNumJoints> infer(const std::array<float, kObsDim> &obs) {
    std::array<int64_t, 2> shape{1, static_cast<int64_t>(kObsDim)};
    auto mem = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    auto tensor = Ort::Value::CreateTensor<float>(
        mem, const_cast<float *>(obs.data()), obs.size(), shape.data(), shape.size());
    const char *ins[] = {input_name_};
    const char *outs[] = {output_name_};
    auto y = session_.Run(Ort::RunOptions{nullptr}, ins, &tensor, 1, outs, 1);
    const float *p = y[0].GetTensorData<float>();
    std::array<float, kNumJoints> action{};
    std::copy(p, p + kNumJoints, action.begin());
    return action;
  }

  const std::array<float, kNumJoints> &default_q() const { return default_q_; }
  const std::array<float, kNumJoints> &action_scale() const { return action_scale_; }
  const std::array<float, kNumJoints> &kp() const { return kp_; }
  const std::array<float, kNumJoints> &kd() const { return kd_; }

 private:
  Ort::Env env_;
  Ort::SessionOptions opts_;
  Ort::Session session_;
  Ort::AllocatedStringPtr input_name_holder_{nullptr};
  Ort::AllocatedStringPtr output_name_holder_{nullptr};
  const char *input_name_{nullptr};
  const char *output_name_{nullptr};
  std::array<float, kNumJoints> default_q_{};
  std::array<float, kNumJoints> action_scale_{};
  std::array<float, kNumJoints> kp_{};
  std::array<float, kNumJoints> kd_{};
};

class BalletUdpReceiver {
 public:
  static constexpr size_t kPacketFloats = 61;
  static constexpr size_t kPacketBytes = kPacketFloats * sizeof(float);

  BalletUdpReceiver(const std::string &host, int port) {
    fd_ = ::socket(AF_INET, SOCK_DGRAM, 0);
    if (fd_ < 0) throw std::runtime_error("socket(AF_INET, SOCK_DGRAM) failed");

    int reuse = 1;
    ::setsockopt(fd_, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));
    const int flags = ::fcntl(fd_, F_GETFL, 0);
    if (flags < 0 || ::fcntl(fd_, F_SETFL, flags | O_NONBLOCK) < 0) {
      ::close(fd_);
      throw std::runtime_error("failed to make UDP socket non-blocking");
    }

    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(static_cast<uint16_t>(port));
    if (host == "0.0.0.0" || host.empty()) {
      addr.sin_addr.s_addr = htonl(INADDR_ANY);
    } else if (::inet_pton(AF_INET, host.c_str(), &addr.sin_addr) != 1) {
      ::close(fd_);
      throw std::runtime_error("udp_host must be an IPv4 address or 0.0.0.0");
    }

    if (::bind(fd_, reinterpret_cast<sockaddr *>(&addr), sizeof(addr)) < 0) {
      const std::string why = std::strerror(errno);
      ::close(fd_);
      throw std::runtime_error(
          "UDP bind " + host + ":" + std::to_string(port) + " failed: " + why);
    }
  }

  ~BalletUdpReceiver() {
    if (fd_ >= 0) ::close(fd_);
  }

  // Training v1 wire ABI:
  //   targets[29] + mask[29] + velocity[vx,vy,yaw][3]
  // Receiver drains the socket and returns the newest valid datagram, matching
  // the last-value semantics of wbc_ballet.teleop.protocol.UdpCommandReceiver.
  bool poll(
      std::array<float, kNumJoints> &targets,
      std::array<float, kNumJoints> &mask,
      std::array<float, 3> &velocity) {
    bool got_valid = false;
    while (true) {
      std::array<unsigned char, kPacketBytes> bytes{};
      const ssize_t n = ::recvfrom(fd_, bytes.data(), bytes.size(), 0, nullptr, nullptr);
      if (n < 0) {
        if (errno == EAGAIN || errno == EWOULDBLOCK) break;
        break;
      }
      if (static_cast<size_t>(n) != kPacketBytes) continue;

      std::array<float, kPacketFloats> values{};
      std::memcpy(values.data(), bytes.data(), kPacketBytes);
      if (!std::all_of(values.begin(), values.end(), [](float x) { return std::isfinite(x); })) {
        continue;
      }

      for (size_t i = 0; i < kNumJoints; ++i) {
        targets[i] = std::clamp(values[i], -1.0f, 1.0f);
        mask[i] = values[kNumJoints + i] >= 0.5f ? 1.0f : 0.0f;
      }
      for (size_t i = 0; i < 3; ++i) velocity[i] = values[2 * kNumJoints + i];
      got_valid = true;
    }
    return got_valid;
  }

 private:
  int fd_{-1};
};

class G1BalletNode : public rclcpp::Node {
 public:
  G1BalletNode() : Node("g1_ballet_onnx") {
    const auto policy_path = declare_parameter<std::string>("policy_path", "policy/policy.onnx");
    lowstate_topic_ = declare_parameter<std::string>("lowstate_topic", "/lowstate");
    lowcmd_topic_ = declare_parameter<std::string>("lowcmd_topic", "/lowcmd");
    udp_host_ = declare_parameter<std::string>("udp_host", "0.0.0.0");
    udp_port_ = declare_parameter<int>("udp_port", 55001);
    enable_topic_ = declare_parameter<std::string>("enable_topic", "/ballet/enable");
    policy_hz_ = declare_parameter<double>("policy_hz", 50.0);
    lowcmd_hz_ = declare_parameter<double>("lowcmd_hz", 500.0);
    ramp_seconds_ = declare_parameter<double>("ramp_seconds", 3.0);
    state_timeout_s_ = declare_parameter<double>("state_timeout_s", 0.15);
    command_timeout_s_ = declare_parameter<double>("command_timeout_s", 0.5);
    max_tilt_rad_ = declare_parameter<double>("max_tilt_rad", 0.65);
    action_clip_abs_ = declare_parameter<double>("action_clip_abs", 0.0);
    target_limit_margin_ = declare_parameter<double>("target_limit_margin", 0.98);
    damping_kd_ = declare_parameter<double>("damping_kd", 2.0);
    ramp_gain_scale_ = declare_parameter<double>("ramp_gain_scale", 0.5);
    policy_gain_scale_ = declare_parameter<double>("policy_gain_scale", 1.0);
    required_mode_machine_ = declare_parameter<int>("required_mode_machine", 5);
    reject_other_lowcmd_publishers_ = declare_parameter<bool>("reject_other_lowcmd_publishers", true);

    if (policy_hz_ <= 0.0 || lowcmd_hz_ <= 0.0 || ramp_seconds_ <= 0.0) {
      throw std::runtime_error("policy_hz, lowcmd_hz and ramp_seconds must be positive");
    }
    if (target_limit_margin_ <= 0.0 || target_limit_margin_ > 1.0) {
      throw std::runtime_error("target_limit_margin must be in (0, 1]");
    }
    if (action_clip_abs_ < 0.0) {
      throw std::runtime_error("action_clip_abs must be >= 0 (0 disables actor clipping)");
    }

    policy_ = std::make_unique<OnnxPolicy>(policy_path);
    RCLCPP_INFO(
        get_logger(), "Loaded ONNX policy and verified ballet 186D/29DoF ABI: %s",
        policy_path.c_str());

    udp_ = std::make_unique<BalletUdpReceiver>(udp_host_, udp_port_);
    RCLCPP_INFO(
        get_logger(),
        "Listening for BALLET game_emulator_run_v1.py UDP on %s:%d "
        "(targets29 + mask29 + velocity3 = 61 float32 / 244 bytes)",
        udp_host_.c_str(), udp_port_);

    lowcmd_pub_ = create_publisher<unitree_hg::msg::LowCmd>(lowcmd_topic_, 10);
    lowstate_sub_ = create_subscription<unitree_hg::msg::LowState>(
        lowstate_topic_, 10,
        [this](unitree_hg::msg::LowState::SharedPtr msg) {
          std::lock_guard<std::mutex> lock(mu_);
          state_ = *msg;
          have_state_ = true;
          state_stamp_ = SteadyClock::now();
        });

    RCLCPP_INFO(
        get_logger(),
        "Robot I/O contract: SUB %s [unitree_hg/msg/LowState] -> actor; "
        "PUB %s [unitree_hg/msg/LowCmd] <- motor targets[0..28]",
        lowstate_topic_.c_str(), lowcmd_topic_.c_str());

    enable_sub_ = create_subscription<std_msgs::msg::Bool>(
        enable_topic_, 10, [this](std_msgs::msg::Bool::SharedPtr msg) {
          std::lock_guard<std::mutex> lock(mu_);
          requested_enable_ = msg->data;
          if (!msg->data) {
            phase_ = Phase::kIdle;
            RCLCPP_WARN(get_logger(), "Policy disabled; damping is used after the first arm.");
          } else {
            RCLCPP_WARN(get_logger(), "Policy enable requested; waiting for all watchdog checks.");
          }
        });

    // As in the reference Unitree deploy, policy inference and low-level command
    // publication run at different rates. Training policy dt is 0.02 s (50 Hz),
    // while Unitree's high-frequency ROS2 low-level example runs at 2 ms.
    lowcmd_timer_ = create_wall_timer(
        std::chrono::duration<double>(1.0 / lowcmd_hz_), [this] { publish_lowcmd_tick(); });

    policy_thread_running_.store(true);
    policy_thread_ = std::thread([this] { policy_loop(); });

    RCLCPP_INFO(
        get_logger(), "Runtime started: policy %.1f Hz, lowcmd %.1f Hz, required_mode_machine=%d",
        policy_hz_, lowcmd_hz_, required_mode_machine_);
  }

  ~G1BalletNode() override {
    policy_thread_running_.store(false);
    if (policy_thread_.joinable()) policy_thread_.join();
  }

 private:
  enum class Phase { kIdle, kRamping, kActive };

  static std::array<float, 3> projected_gravity(const std::array<double, 4> &q) {
    // Unitree LowState quaternion is [w, x, y, z].  Project world gravity
    // (0,0,-1) into the body frame using the inverse/conjugate rotation.
    const float w = static_cast<float>(q[0]);
    const float x = -static_cast<float>(q[1]);
    const float y = -static_cast<float>(q[2]);
    const float z = -static_cast<float>(q[3]);
    const float x2 = x * x;
    const float y2 = y * y;
    const float z2 = z * z;
    const float w2 = w * w;
    const float xz = x * z;
    const float yz = y * z;
    const float wx = w * x;
    const float wy = w * y;
    return {
        -2.0f * (xz + wy),
        -2.0f * (yz - wx),
        -(w2 - x2 - y2 + z2),
    };
  }

  static bool fresh(const SteadyTime &stamp, double timeout_s, const SteadyTime &now) {
    return std::chrono::duration<double>(now - stamp).count() <= timeout_s;
  }

  static unitree_hg::msg::LowCmd zero_lowcmd(uint8_t mode_machine) {
    unitree_hg::msg::LowCmd cmd;
    cmd.mode_pr = 0;  // PR mode, matching Unitree G1 low-level examples.
    cmd.mode_machine = mode_machine;
    for (size_t i = 0; i < 35; ++i) {
      cmd.motor_cmd[i].mode = 0;  // unused channels stay passive/disabled
      cmd.motor_cmd[i].q = 0.0f;
      cmd.motor_cmd[i].dq = 0.0f;
      cmd.motor_cmd[i].tau = 0.0f;
      cmd.motor_cmd[i].kp = 0.0f;
      cmd.motor_cmd[i].kd = 0.0f;
      cmd.motor_cmd[i].reserve = 0;
    }
    for (auto &v : cmd.reserve) v = 0;
    return cmd;
  }

  void publish_damping(const unitree_hg::msg::LowState &state) {
    auto cmd = zero_lowcmd(state.mode_machine);
    for (size_t i = 0; i < kNumJoints; ++i) {
      cmd.motor_cmd[i].mode = 1;
      cmd.motor_cmd[i].q = state.motor_state[i].q;
      cmd.motor_cmd[i].kd = static_cast<float>(damping_kd_);
    }
    set_crc(cmd);
    lowcmd_pub_->publish(cmd);
  }

  void publish_position(
      const unitree_hg::msg::LowState &state,
      const std::array<float, kNumJoints> &q_des,
      float gain_scale) {
    auto cmd = zero_lowcmd(state.mode_machine);
    for (size_t i = 0; i < kNumJoints; ++i) {
      cmd.motor_cmd[i].mode = 1;
      cmd.motor_cmd[i].q = q_des[i];
      cmd.motor_cmd[i].dq = 0.0f;
      cmd.motor_cmd[i].tau = 0.0f;
      cmd.motor_cmd[i].kp = policy_->kp()[i] * gain_scale;
      cmd.motor_cmd[i].kd = policy_->kd()[i] * gain_scale;
    }
    set_crc(cmd);
    lowcmd_pub_->publish(cmd);
  }

  void fail_safe(const std::string &reason) {
    bool was_running = false;
    {
      std::lock_guard<std::mutex> lock(mu_);
      was_running = requested_enable_ || phase_ != Phase::kIdle;
      requested_enable_ = false;
      phase_ = Phase::kIdle;
    }
    if (was_running) {
      RCLCPP_ERROR(get_logger(), "FAIL-SAFE: %s; re-enable is required", reason.c_str());
    }
  }

  void publish_lowcmd_tick() {
    unitree_hg::msg::LowState state;
    std::array<float, kNumJoints> q_des{};
    Phase phase = Phase::kIdle;
    bool have_state = false;
    bool ever_armed = false;
    SteadyTime state_stamp{};
    {
      std::lock_guard<std::mutex> lock(mu_);
      state = state_;
      q_des = q_desired_;
      phase = phase_;
      have_state = have_state_;
      ever_armed = ever_armed_;
      state_stamp = state_stamp_;
    }

    if (!have_state || !ever_armed) return;

    const auto now = SteadyClock::now();
    if (!fresh(state_stamp, state_timeout_s_, now) || phase == Phase::kIdle) {
      // q is irrelevant because kp=0, but using the last measured q mirrors the
      // reference Passive state and avoids a position discontinuity if gains change.
      publish_damping(state);
      return;
    }

    const float gain_scale = static_cast<float>(
        phase == Phase::kRamping ? ramp_gain_scale_ : policy_gain_scale_);
    publish_position(state, q_des, gain_scale);
  }

  void policy_loop() {
    using Duration = SteadyClock::duration;
    const Duration period = std::chrono::duration_cast<Duration>(
        std::chrono::duration<double>(1.0 / policy_hz_));
    auto next = SteadyClock::now();

    while (policy_thread_running_.load()) {
      next += period;
      try {
        policy_tick();
      } catch (const std::exception &e) {
        fail_safe(std::string("policy loop exception: ") + e.what());
      }
      std::this_thread::sleep_until(next);

      // If the machine was paused/debugged for a long time, do not busy-loop
      // trying to catch up missed policy ticks.
      const auto now = SteadyClock::now();
      if (next + period < now) next = now;
    }
  }

  void policy_tick() {
    // First drain all queued v1 gamepad datagrams and keep the newest valid one.
    std::array<float, kNumJoints> udp_targets{};
    std::array<float, kNumJoints> udp_mask{};
    std::array<float, 3> udp_velocity{};
    if (udp_->poll(udp_targets, udp_mask, udp_velocity)) {
      std::lock_guard<std::mutex> lock(mu_);
      targets_ = udp_targets;
      mask_ = udp_mask;
      velocity_cmd_ = udp_velocity;
      have_command_ = true;
      command_stamp_ = SteadyClock::now();
    }

    unitree_hg::msg::LowState state;
    std::array<float, 3> velocity_cmd{};
    std::array<float, kNumJoints> targets{};
    std::array<float, kNumJoints> mask{};
    std::array<float, kNumJoints> last_action{};
    std::array<float, kNumJoints> ramp_q0{};
    bool requested_enable = false;
    bool have_state = false;
    bool have_command = false;
    Phase phase = Phase::kIdle;
    SteadyTime state_stamp{};
    SteadyTime command_stamp{};
    SteadyTime ramp_start{};

    {
      std::lock_guard<std::mutex> lock(mu_);
      state = state_;
      velocity_cmd = velocity_cmd_;
      targets = targets_;
      mask = mask_;
      last_action = last_action_;
      ramp_q0 = ramp_q0_;
      requested_enable = requested_enable_;
      have_state = have_state_;
      have_command = have_command_;
      phase = phase_;
      state_stamp = state_stamp_;
      command_stamp = command_stamp_;
      ramp_start = ramp_start_;
    }

    if (!have_state) return;
    const auto now = SteadyClock::now();

    if (!fresh(state_stamp, state_timeout_s_, now)) {
      if (requested_enable) fail_safe("LowState missing/stale");
      return;
    }
    if (!requested_enable) return;

    if (reject_other_lowcmd_publishers_ && this->count_publishers(lowcmd_topic_) > 1) {
      fail_safe("another /lowcmd publisher is present; stop competing low-level controllers");
      return;
    }

    if (required_mode_machine_ >= 0 &&
        static_cast<int>(state.mode_machine) != required_mode_machine_) {
      fail_safe(
          "mode_machine mismatch: got " + std::to_string(static_cast<int>(state.mode_machine)) +
          ", expected " + std::to_string(required_mode_machine_));
      return;
    }

    if (!have_command || !fresh(command_stamp, command_timeout_s_, now)) {
      fail_safe("BALLET game_emulator_run_v1.py UDP missing/stale");
      return;
    }

    const float roll = state.imu_state.rpy[0];
    const float pitch = state.imu_state.rpy[1];
    if (!std::isfinite(roll) || !std::isfinite(pitch) ||
        std::abs(roll) > max_tilt_rad_ || std::abs(pitch) > max_tilt_rad_) {
      fail_safe("tilt limit exceeded or invalid IMU RPY");
      return;
    }

    if (phase == Phase::kIdle) {
      std::array<float, kNumJoints> q0{};
      for (size_t i = 0; i < kNumJoints; ++i) q0[i] = state.motor_state[i].q;
      {
        std::lock_guard<std::mutex> lock(mu_);
        // The enable callback may have cancelled the request while we were checking.
        if (!requested_enable_) return;
        ramp_q0_ = q0;
        q_desired_ = q0;
        ramp_start_ = now;
        last_action_.fill(0.0f);
        ever_armed_ = true;
        phase_ = Phase::kRamping;
      }
      RCLCPP_WARN(
          get_logger(), "ARMED: ramping current pose -> ONNX default pose for %.2f s",
          ramp_seconds_);
      return;
    }

    if (phase == Phase::kRamping) {
      const float alpha = std::clamp(
          static_cast<float>(std::chrono::duration<double>(now - ramp_start).count() /
                             ramp_seconds_),
          0.0f, 1.0f);
      const float smooth = alpha * alpha * (3.0f - 2.0f * alpha);
      std::array<float, kNumJoints> q_des{};
      for (size_t i = 0; i < kNumJoints; ++i) {
        q_des[i] = ramp_q0[i] + smooth * (policy_->default_q()[i] - ramp_q0[i]);
      }
      {
        std::lock_guard<std::mutex> lock(mu_);
        if (!requested_enable_ || phase_ != Phase::kRamping) return;
        q_desired_ = q_des;
        if (alpha >= 1.0f) {
          last_action_.fill(0.0f);
          phase_ = Phase::kActive;
        }
      }
      if (alpha >= 1.0f) RCLCPP_WARN(get_logger(), "POLICY ACTIVE");
      return;
    }

    // ---------------- exact BALLET actor observation ABI: 186 floats ----------------
    std::array<float, kObsDim> obs{};
    size_t k = 0;
    const auto put3 = [&](const std::array<float, 3> &v) {
      for (float x : v) obs[k++] = x;
    };

    // 1) base_ang_vel [3] -- metadata/config term name; physical source is IMU gyro.
    put3({
        state.imu_state.gyroscope[0],
        state.imu_state.gyroscope[1],
        state.imu_state.gyroscope[2],
    });

    // 2) imu_lin_acc [3] -- training term clips [-30,30], then scale=0.1.
    put3({
        0.1f * std::clamp(state.imu_state.accelerometer[0], -30.0f, 30.0f),
        0.1f * std::clamp(state.imu_state.accelerometer[1], -30.0f, 30.0f),
        0.1f * std::clamp(state.imu_state.accelerometer[2], -30.0f, 30.0f),
    });

    // 3) projected_gravity [3]
    const std::array<double, 4> quat = {
        state.imu_state.quaternion[0],
        state.imu_state.quaternion[1],
        state.imu_state.quaternion[2],
        state.imu_state.quaternion[3],
    };
    put3(projected_gravity(quat));

    // 4) velocity_commands [3] -- internally training command[0:3].
    put3(velocity_cmd);

    // 5) joint_pos [29] = joint_pos_rel = q - default_q.
    for (size_t i = 0; i < kNumJoints; ++i) {
      obs[k++] = state.motor_state[i].q - policy_->default_q()[i];
    }

    // 6) joint_vel [29] = dq (default joint velocity is zero).
    for (size_t i = 0; i < kNumJoints; ++i) obs[k++] = state.motor_state[i].dq;

    // 7) actions [29] = previous policy action (raw by default, as during training).
    for (float x : last_action) obs[k++] = x;

    // 8) axis_actual_normalized [29].
    for (size_t i = 0; i < kNumJoints; ++i) {
      const float normalized =
          2.0f * (state.motor_state[i].q - kJointLower[i]) /
              (kJointUpper[i] - kJointLower[i]) -
          1.0f;
      obs[k++] = std::clamp(normalized, -1.0f, 1.0f);
    }

    // 9) axis_target_normalized [29] = target hard-gated by mask.
    for (size_t i = 0; i < kNumJoints; ++i) {
      obs[k++] = mask[i] >= 0.5f ? targets[i] : 0.0f;
    }

    // 10) axis_mask [29].
    for (float x : mask) obs[k++] = x;

    if (k != kObsDim) {
      fail_safe("internal observation dimension error");
      return;
    }
    if (!std::all_of(obs.begin(), obs.end(), [](float x) { return std::isfinite(x); })) {
      fail_safe("NaN/Inf observation");
      return;
    }

    auto action = policy_->infer(obs);
    if (!finite_array(action)) {
      fail_safe("NaN/Inf policy action");
      return;
    }

    std::array<float, kNumJoints> q_des{};
    for (size_t i = 0; i < kNumJoints; ++i) {
      // Training's RslRlOnPolicyRunnerCfg does not set clip_actions, so actor
      // clipping is disabled by default here too.  A positive value is an
      // optional deployment-only safety override.
      if (action_clip_abs_ > 0.0) {
        const float clip = static_cast<float>(action_clip_abs_);
        action[i] = std::clamp(action[i], -clip, clip);
      }

      const float q = policy_->default_q()[i] + policy_->action_scale()[i] * action[i];
      const float mid = 0.5f * (kJointLower[i] + kJointUpper[i]);
      const float half =
          0.5f * (kJointUpper[i] - kJointLower[i]) * static_cast<float>(target_limit_margin_);
      q_des[i] = std::clamp(q, mid - half, mid + half);
    }

    {
      std::lock_guard<std::mutex> lock(mu_);
      if (!requested_enable_ || phase_ != Phase::kActive) return;
      last_action_ = action;
      q_desired_ = q_des;
    }
  }

  std::unique_ptr<OnnxPolicy> policy_;
  std::unique_ptr<BalletUdpReceiver> udp_;

  std::mutex mu_;
  unitree_hg::msg::LowState state_{};
  std::array<float, 3> velocity_cmd_{};
  std::array<float, kNumJoints> targets_{};
  std::array<float, kNumJoints> mask_{};
  std::array<float, kNumJoints> last_action_{};
  std::array<float, kNumJoints> ramp_q0_{};
  std::array<float, kNumJoints> q_desired_{};

  bool have_state_{false};
  bool have_command_{false};
  bool requested_enable_{false};
  bool ever_armed_{false};
  Phase phase_{Phase::kIdle};
  SteadyTime state_stamp_{};
  SteadyTime command_stamp_{};
  SteadyTime ramp_start_{};

  std::string lowstate_topic_;
  std::string lowcmd_topic_;
  std::string enable_topic_;
  std::string udp_host_;
  int udp_port_{55001};
  double policy_hz_{50.0};
  double lowcmd_hz_{500.0};
  double ramp_seconds_{3.0};
  double state_timeout_s_{0.15};
  double command_timeout_s_{0.5};
  double max_tilt_rad_{0.65};
  double action_clip_abs_{0.0};
  double target_limit_margin_{0.98};
  double damping_kd_{2.0};
  double ramp_gain_scale_{0.5};
  double policy_gain_scale_{1.0};
  int required_mode_machine_{5};
  bool reject_other_lowcmd_publishers_{true};

  std::atomic<bool> policy_thread_running_{false};
  std::thread policy_thread_;

  rclcpp::Publisher<unitree_hg::msg::LowCmd>::SharedPtr lowcmd_pub_;
  rclcpp::Subscription<unitree_hg::msg::LowState>::SharedPtr lowstate_sub_;
  rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr enable_sub_;
  rclcpp::TimerBase::SharedPtr lowcmd_timer_;
};

}  // namespace g1_ballet

int main(int argc, char **argv) {
  rclcpp::init(argc, argv);
  try {
    rclcpp::spin(std::make_shared<g1_ballet::G1BalletNode>());
  } catch (const std::exception &e) {
    std::cerr << "FATAL: " << e.what() << std::endl;
    rclcpp::shutdown();
    return 1;
  }
  rclcpp::shutdown();
  return 0;
}
